import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentDocSidebar: [
    {
      type: 'category',
      label: '◉ 시작하기',
      collapsed: false,
      collapsible: true,
      items: [
        'documents/getting-started/overview',
      ],
    },
    {
      type: 'category',
      label: '◉ 개발 가이드',
      collapsed: false,
      collapsible: true,
      items: [
        'documents/index',
        {
          type: 'category',
          label: '• Form 전송 방법',
          collapsed: true,
          collapsible: true,
          items: [
            'documents/index',
          ],
        },
        {
          type: 'category',
          label: '• Dialog 띄우기',
          collapsed: true,
          collapsible: true,
          items: [
            'documents/index',
          ],
        },
        'documents/index',
        'documents/index',
      ],
    },
  ],
  componentsDocSidebar: [
    'components/index',
  ],
  apiDocSidebar: [
    'apis/index',
  ],
  taskDocSidebar: [
    'task/intro',
    {
      type: 'category',
      label: '◉ Micro Frontend 준비',
      collapsed: true,
      collapsible: true,
      items: [
        'task/ready/set-mf-proj/set-docusaurus-docs',
        'task/ready/set-mf-proj/set-mf-lib-shared',
        'task/ready/set-mf-proj/set-mf-app-main',
      ],
    },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
